// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (user_id, friend_id, status)
VALUES ($1, $2, $3)
RETURNING id, user_id, friend_id, status, created_at
`

type CreateFriendshipParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FriendID pgtype.UUID `json:"friend_id"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserID, arg.FriendID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_id, status, created_at FROM friendships
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
`

type GetFriendshipParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FriendID pgtype.UUID `json:"friend_id"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listUserFriends = `-- name: ListUserFriends :many
SELECT u.id, u.username, u.email, u.password_hash, u.created_at, u.updated_at FROM users u
INNER JOIN friendships f ON u.id = f.friend_id
WHERE f.user_id = $1 AND f.status = 'accepted'
UNION
SELECT u.id, u.username, u.email, u.password_hash, u.created_at, u.updated_at FROM users u
INNER JOIN friendships f ON u.id = f.user_id
WHERE f.friend_id = $1 AND f.status = 'accepted'
`

func (q *Queries) ListUserFriends(ctx context.Context, userID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUserFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :exec
UPDATE friendships SET status = $2 WHERE id = $1
`

type UpdateFriendshipStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error {
	_, err := q.db.Exec(ctx, updateFriendshipStatus, arg.ID, arg.Status)
	return err
}
