// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error)
	GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListMessagesBetweenUsers(ctx context.Context, arg ListMessagesBetweenUsersParams) ([]Message, error)
	ListUserFriends(ctx context.Context, userID pgtype.UUID) ([]User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
}

var _ Querier = (*Queries)(nil)
